/-
# The null reduction is a free parameter: NULL_RED ∈ [3..10], both parities

`Shortest.lean`'s header and `formal/README.md` claimed **"an odd null
reduction is load-bearing"** for distance-to-mate optimality: an even
reduction would supposedly let a virtual line reach a mate value of the
wrong rung parity and collapse `leastMate_value_separation`'s gap to
exactly the driver's tolerance.  This file replaces that claim with a
theorem.  The mate-liveness results hold for EVERY null reduction
`R ≥ 1` — in particular the whole tuning range `[3..10]`, even values
included — and the shipped constant `3` is recovered as one instance.

Why the parity fear was never realized by the mechanized proofs:

1. **The suppression already bars the positive band at every `R`.**
   The declared function admits the pass term only strictly below
   `MATE_LOWER` (`nullTermDR_lt_ML`, the value-side reading of the
   engine's `min(pos.score + EVAL_ROUGHNESS, ·)` cap, which
   `EvalBounds` keeps sub-band).  A mate-band fold value therefore
   always names a REAL move — for any reduction.

2. **The negative band is inert in the max-fold.**  A deeply negative
   pass term can only LOWER the initial accumulator's claim on the
   max; it never raises a declared value, at any parity.

3. **Under `NoZugzwang` the pass term never decides anything.**  The
   accuracy layer proves the null-inclusive value EQUAL to the
   real-move value (`nullValueR_eq_realValue_of_noZugzwangR`, the
   `R`-generic port of `nullValue_eq_realValue_of_noZugzwang`), so
   every mate value is a real-move value and the rung grid is
   generated by `ForcedMate` alone — whose parity comes from the GAME
   (`mate` costs one ply, `step` two), not from the search.

The transfer is architectural, not re-proved: `NoZugzwang` at the
guard `fun _ => false` is VACUOUS (`noZugzwang_guardOff`), and with the
guard off the declared function IS `negamaxD2`
(`nullValueD2_guardOff_eq_negamax`).  So every existing mate theorem,
already quantified over an arbitrary guard, instantiates at guard-off
with its null machinery inert; the `R`-engine's declared value equals
that instance under its own `NoZugzwangR R`.  The wrappers below carry
the statements users want, at every `R`.

What is genuinely `R`-dependent — stated, not hidden: `NoZugzwangR R`
evaluates the pass at depth `d - (R - 1)`, so at different reductions
one buys a slightly different zugzwang premise (same shape, different
pass horizon).  That is the entire residue of the constant.  Nothing
about `R`'s parity is consumed anywhere, because under the premise the
pass term is never the strict maximum and outside the premise the
theorems were never claimed at `R = 3` either.

No code change accompanies this file: the engine needs none.  The
`max(1 - MATE_LOWER, ·)` floor once proposed for even reductions
(closed PR #232) is not required — the two-band analysis above is
exactly why — and `sunfish.py` is untouched.

Note on the depth arithmetic: the pass child runs at `d - (R - 1)`,
which for every `R ≥ 1` equals the engine-shaped `d + 1 - R` (Nat
subtraction) and makes termination unconditional.  `R = 0` degenerates
to `R = 1` and is outside the stated range.
-/

import Sunfish.Shortest

namespace Sunfish

/-! ### The `R`-parametrized declared value -/

/-- **The null-inclusive declared value at reduction `R`**: verbatim
`nullValueD2` with the pass searched at `d - (R - 1)` = `d + 1 - R`
instead of the shipped `d + 1 - 3`.  Same king-capture normalization,
same terminal classification, same fold, same sub-band suppression of
the pass term. -/
def nullValueDR (G : QSGame) (guard : G.Pos → Bool) (R : Nat) :
    Nat → G.Pos → Int
  | 0, p =>
    if G.eval p ≤ -MATE_LOWER then -MATE_UPPER
    else if hasKingCapture G.toNullGame.toGame p = true then MATE_UPPER
    else G.eval p
  | d + 1, p =>
    if G.eval p ≤ -MATE_LOWER then -MATE_UPPER
    else if hasKingCapture G.toNullGame.toGame p = true then MATE_UPPER
    else if allIllegalB G p = true then terminalValue G (d + 1) p
    else
      foldMax (fun m => -(nullValueDR G guard R d m))
        (movesAbove G (val_lower (d + 1)) p)
        (if guard p = true ∧ 2 < d + 1 then
          (if -(nullValueDR G guard R (d - (R - 1)) (G.pass p)) < MATE_LOWER then
            max LOSS (-(nullValueDR G guard R (d - (R - 1)) (G.pass p)))
          else LOSS)
        else LOSS)
termination_by d _ => d
decreasing_by all_goals omega

/-- The pass term at reduction `R`, named. -/
def nullTermDR (G : QSGame) (guard : G.Pos → Bool) (R d : Nat)
    (p : G.Pos) : Int :=
  if guard p = true ∧ 2 < d + 1 then
    (if -(nullValueDR G guard R (d - (R - 1)) (G.pass p)) < MATE_LOWER then
      max LOSS (-(nullValueDR G guard R (d - (R - 1)) (G.pass p)))
    else LOSS)
  else LOSS

/-! ### Branch lemmas, ports of `nullValueD2`'s -/

theorem nullValueDR_kingGone (G : QSGame) (guard : G.Pos → Bool)
    (R d : Nat) (p : G.Pos) (h : G.eval p ≤ -MATE_LOWER) :
    nullValueDR G guard R d p = -MATE_UPPER := by
  cases d with
  | zero => simp only [nullValueDR]; rw [if_pos h]
  | succ d => simp only [nullValueDR]; rw [if_pos h]

theorem nullValueDR_of_capture (G : QSGame) (guard : G.Pos → Bool)
    (R d : Nat) (p : G.Pos) (hkg : ¬ (G.eval p ≤ -MATE_LOWER))
    (hcap : hasKingCapture G.toNullGame.toGame p = true) :
    nullValueDR G guard R d p = MATE_UPPER := by
  cases d with
  | zero => simp only [nullValueDR]; rw [if_neg hkg, if_pos hcap]
  | succ d => simp only [nullValueDR]; rw [if_neg hkg, if_pos hcap]

theorem nullValueDR_of_allIllegal (G : QSGame) (guard : G.Pos → Bool)
    (R d : Nat) (p : G.Pos)
    (hkg : ¬ (G.eval p ≤ -MATE_LOWER))
    (hcap : ¬ (hasKingCapture G.toNullGame.toGame p = true))
    (hai : allIllegalB G p = true) :
    nullValueDR G guard R (d + 1) p = terminalValue G (d + 1) p := by
  simp only [nullValueDR]
  rw [if_neg hkg, if_neg hcap, if_pos hai]

theorem nullValueDR_of_fold (G : QSGame) (guard : G.Pos → Bool)
    (R d : Nat) (p : G.Pos)
    (hkg : ¬ (G.eval p ≤ -MATE_LOWER))
    (hcap : ¬ (hasKingCapture G.toNullGame.toGame p = true))
    (hai : allIllegalB G p = false) :
    nullValueDR G guard R (d + 1) p
      = foldMax (fun m => -(nullValueDR G guard R d m))
          (movesAbove G (val_lower (d + 1)) p) (nullTermDR G guard R d p) := by
  simp only [nullValueDR]
  rw [if_neg hkg, if_neg hcap, if_neg (by simp [hai])]
  rfl

theorem nullTermDR_ge_LOSS (G : QSGame) (guard : G.Pos → Bool)
    (R d : Nat) (p : G.Pos) : LOSS ≤ nullTermDR G guard R d p := by
  simp only [nullTermDR]
  by_cases h1 : guard p = true ∧ 2 < d + 1
  · rw [if_pos h1]
    by_cases h2 : -(nullValueDR G guard R (d - (R - 1)) (G.pass p)) < MATE_LOWER
    · rw [if_pos h2]; omega
    · rw [if_neg h2]; omega
  · rw [if_neg h1]; omega

/-- **The suppression at every reduction**: the pass term is always
strictly below the mate band, so a band-value fold names a real move —
independently of `R`, hence independently of `R`'s parity. -/
theorem nullTermDR_lt_ML (G : QSGame) (guard : G.Pos → Bool)
    (R d : Nat) (p : G.Pos) : nullTermDR G guard R d p < MATE_LOWER := by
  have hMU : MATE_UPPER = 69290 := rfl
  have hML : MATE_LOWER = 47923 := rfl
  have hLOSS : LOSS = -MATE_UPPER := rfl
  simp only [nullTermDR]
  by_cases h1 : guard p = true ∧ 2 < d + 1
  · rw [if_pos h1]
    by_cases h2 : -(nullValueDR G guard R (d - (R - 1)) (G.pass p)) < MATE_LOWER
    · rw [if_pos h2]; omega
    · rw [if_neg h2]; omega
  · rw [if_neg h1]; omega

/-! ### The shipped constant is the `R = 3` instance -/

/-- `nullValueDR` at `R = 3` IS the shipped model `nullValueD2`:
`d - (3 - 1) = d + 1 - 3` in `Nat`, and the recursions coincide. -/
theorem nullValueDR_three (G : QSGame) (guard : G.Pos → Bool) :
    ∀ (d : Nat) (p : G.Pos),
      nullValueDR G guard 3 d p = nullValueD2 G guard d p := by
  intro d
  induction d using Nat.strongRecOn with
  | _ d ih =>
    intro p
    cases d with
    | zero => simp only [nullValueDR, nullValueD2]
    | succ d =>
      by_cases hkg : G.eval p ≤ -MATE_LOWER
      · rw [nullValueDR_kingGone G guard 3 (d + 1) p hkg,
          nullValueD2_kingGone G guard (d + 1) p hkg]
      · by_cases hcap : hasKingCapture G.toNullGame.toGame p = true
        · rw [nullValueDR_of_capture G guard 3 (d + 1) p hkg hcap,
            nullValueD2_of_capture G guard (d + 1) p hkg hcap]
        · cases hai : allIllegalB G p with
          | true =>
            rw [nullValueDR_of_allIllegal G guard 3 d p hkg hcap hai,
              nullValueD2_of_allIllegal G guard d p hkg hcap hai]
          | false =>
            rw [nullValueDR_of_fold G guard 3 d p hkg hcap hai,
              nullValueD2_of_fold G guard d p hkg hcap hai]
            have hinit : nullTermDR G guard 3 d p = nullTermD2 G guard d p := by
              simp only [nullTermDR, nullTermD2]
              have hdep : d - (3 - 1) = d + 1 - 3 := by omega
              rw [hdep, ih (d + 1 - 3) (by omega) (G.pass p)]
            rw [hinit]
            exact foldMax_congr _ _ _ _ (fun m _ => by rw [ih d (by omega) m])

/-! ### The `R`-matched zugzwang premise, and the accuracy equality -/

/-- **`NoZugzwang` at reduction `R`** (same shape as the shipped
premise, pass horizon at `d - (R - 1)`): the raw pass term never
strictly beats the real-move fold.  This is the ONE place the tuning
constant genuinely lives. -/
def NoZugzwangR (G : QSGame) (guard : G.Pos → Bool) (R : Nat) : Prop :=
  ∀ (d : Nat) (p : G.Pos),
    ¬ (G.eval p ≤ -MATE_LOWER) →
    ¬ (hasKingCapture G.toNullGame.toGame p = true) →
    allIllegalB G p = false → guard p = true → 2 < d + 1 →
    -(nullValueDR G guard R (d - (R - 1)) (G.pass p))
      ≤ foldMax (fun m => -(nullValueDR G guard R d m))
          (movesAbove G (val_lower (d + 1)) p) LOSS

/-- At `R = 3` the premise is the shipped `NoZugzwang`. -/
theorem noZugzwangR_three (G : QSGame) (guard : G.Pos → Bool) :
    NoZugzwangR G guard 3 ↔ NoZugzwang G guard := by
  constructor <;> intro h d p hkg hcap hai hg hd <;>
    have hdep : d - (3 - 1) = d + 1 - 3 := by omega
  · have h' := h d p hkg hcap hai hg hd
    rw [hdep, nullValueDR_three G guard (d + 1 - 3) (G.pass p)] at h'
    calc -(nullValueD2 G guard (d + 1 - 3) (G.pass p))
        ≤ foldMax (fun m => -(nullValueDR G guard 3 d m))
            (movesAbove G (val_lower (d + 1)) p) LOSS := h'
      _ = foldMax (fun m => -(nullValueD2 G guard d m))
            (movesAbove G (val_lower (d + 1)) p) LOSS :=
          foldMax_congr _ _ _ _ (fun m _ => by
            rw [nullValueDR_three G guard d m])
  · have h' := h d p hkg hcap hai hg hd
    rw [hdep, nullValueDR_three G guard (d + 1 - 3) (G.pass p)]
    calc -(nullValueD2 G guard (d + 1 - 3) (G.pass p))
        ≤ foldMax (fun m => -(nullValueD2 G guard d m))
            (movesAbove G (val_lower (d + 1)) p) LOSS := h'
      _ = foldMax (fun m => -(nullValueDR G guard 3 d m))
            (movesAbove G (val_lower (d + 1)) p) LOSS :=
          foldMax_congr _ _ _ _ (fun m _ => by
            rw [nullValueDR_three G guard d m])

/-- **The accuracy equality at every reduction** — the `R`-generic port
of `nullValue_eq_realValue_of_noZugzwang`, token-for-token: under the
`R`-matched premise the pass term never wins the max, so the
null-inclusive value IS the real-move value.  Note what the proof does
NOT use: `R`'s value, and in particular `R`'s parity. -/
theorem nullValueR_eq_realValue_of_noZugzwangR (G : QSGame)
    (guard : G.Pos → Bool) (R : Nat) (hZ : NoZugzwangR G guard R) :
    ∀ (d : Nat) (p : G.Pos), nullValueDR G guard R d p = negamaxD2 G d p := by
  have hLOSS : LOSS = -MATE_UPPER := rfl
  intro d
  induction d using Nat.strongRecOn with
  | _ d ih =>
    intro p
    cases d with
    | zero => simp only [nullValueDR, negamaxD2]
    | succ d =>
      by_cases hkg : G.eval p ≤ -MATE_LOWER
      · rw [nullValueDR_kingGone G guard R (d + 1) p hkg,
          negamaxD2_kingGone G (d + 1) p hkg]
      · by_cases hcap : hasKingCapture G.toNullGame.toGame p = true
        · rw [nullValueDR_of_capture G guard R (d + 1) p hkg hcap,
            negamaxD2_of_capture G (d + 1) p hkg hcap]
        · cases hai : allIllegalB G p with
          | true =>
            rw [nullValueDR_of_allIllegal G guard R d p hkg hcap hai,
              negamaxD2_of_allIllegal G d p hkg hcap hai]
          | false =>
            rw [nullValueDR_of_fold G guard R d p hkg hcap hai,
              negamaxD2_of_fold G d p hkg hcap hai]
            have hsplit := foldMax_init_split
              (fun m => -(nullValueDR G guard R d m))
              (movesAbove G (val_lower (d + 1)) p) (nullTermDR G guard R d p)
              (nullTermDR_ge_LOSS G guard R d p)
            have hcongr := foldMax_congr (fun m => -(nullValueDR G guard R d m))
              (fun m => -(negamaxD2 G d m))
              (movesAbove G (val_lower (d + 1)) p) LOSS
              (fun m _ => by
                show -(nullValueDR G guard R d m) = -(negamaxD2 G d m)
                rw [ih d (by omega) m])
            have hT : nullTermDR G guard R d p
                ≤ foldMax (fun m => -(nullValueDR G guard R d m))
                    (movesAbove G (val_lower (d + 1)) p) LOSS := by
              have hfl := foldMax_ge_init (fun m => -(nullValueDR G guard R d m))
                (movesAbove G (val_lower (d + 1)) p) LOSS
              by_cases hen : guard p = true ∧ 2 < d + 1
              · by_cases hml : -(nullValueDR G guard R (d - (R - 1)) (G.pass p))
                    < MATE_LOWER
                · have hT' : nullTermDR G guard R d p
                      = max LOSS
                          (-(nullValueDR G guard R (d - (R - 1)) (G.pass p))) := by
                    simp only [nullTermDR]
                    rw [if_pos hen, if_pos hml]
                  have hZ' := hZ d p hkg hcap hai hen.1 hen.2
                  rw [hT']
                  omega
                · have hT' : nullTermDR G guard R d p = LOSS := by
                    simp only [nullTermDR]
                    rw [if_pos hen, if_neg hml]
                  rw [hT']
                  omega
              · have hT' : nullTermDR G guard R d p = LOSS := by
                  simp only [nullTermDR]
                  rw [if_neg hen]
                rw [hT']
                omega
            omega

/-! ### The guard-off instance: vacuous premise, inert null machinery -/

/-- With the guard identically `false` the shipped `NoZugzwang` premise
is VACUOUS: its `guard p = true` hypothesis is absurd. -/
theorem noZugzwang_guardOff (G : QSGame) :
    NoZugzwang G (fun _ => false) := by
  intro d p _ _ _ hg _
  exact absurd hg (by simp)

/-- With the guard identically `false` the shipped declared value IS
the real-move value: the pass branch never opens. -/
theorem nullValueD2_guardOff_eq_negamax (G : QSGame) :
    ∀ (d : Nat) (p : G.Pos),
      nullValueD2 G (fun _ => false) d p = negamaxD2 G d p :=
  nullValue_eq_realValue_of_noZugzwang G (fun _ => false)
    (noZugzwang_guardOff G)

/-- **The transfer**: under its own premise, the `R`-engine's declared
value coincides with the guard-off instance of the shipped model, at
every depth and position.  Every guard-quantified mate theorem now
applies to `nullValueDR R` through this equality. -/
theorem nullValueDR_eq_guardOff (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (hZ : NoZugzwangR G guard R) (d : Nat) (p : G.Pos) :
    nullValueDR G guard R d p = nullValueD2 G (fun _ => false) d p := by
  rw [nullValueR_eq_realValue_of_noZugzwangR G guard R hZ d p,
    nullValueD2_guardOff_eq_negamax G d p]

/-! ### The mate spine at every reduction -/

/-- Mate-in-`k` completeness at reduction `R`. -/
theorem forcedMate_completeR (G : QSGame) (guard : G.Pos → Bool) (R : Nat)
    (hF : ValFloor G 192) (hZ : NoZugzwangR G guard R)
    {k : Nat} {p : G.Pos} (hFM : ForcedMate G k p) :
    ∀ D : Nat, k + 1 ≤ D → mateFloor D k ≤ nullValueDR G guard R D p := by
  intro D hD
  rw [nullValueR_eq_realValue_of_noZugzwangR G guard R hZ D p]
  exact forcedMate_negamaxD2 G hF hFM D hD

/-- No false mates, with the distance, at reduction `R`. -/
theorem forcedMate_of_value_distR (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard R)
    (D t : Nat) (p : G.Pos)
    (hcapf : hasKingCapture G.toNullGame.toGame p = false)
    (hband : MATE_LOWER + (t : Int) * EVAL_ROUGHNESS
      ≤ nullValueDR G guard R D p) :
    ∃ n, 1 ≤ n ∧ n + t ≤ D ∧ ForcedMate G n p := by
  rw [nullValueDR_eq_guardOff G guard R hZ D p] at hband
  exact forcedMate_of_value_dist G (fun _ => false) hF hQ hNM D t p hcapf hband

/-- Block exactness at reduction `R`: the declared value's rung index
is exactly `D - k` at the least mate distance. -/
theorem leastMate_value_blockR (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard R)
    {k D : Nat} {p : G.Pos}
    (hcapf : hasKingCapture G.toNullGame.toGame p = false)
    (hLM : LeastMate G k p) (hkD : k + 1 ≤ D)
    (hspan : (D : Int) * EVAL_ROUGHNESS ≤ 21366) :
    MATE_LOWER + ((D : Int) - (k : Int)) * EVAL_ROUGHNESS
        ≤ nullValueDR G guard R D p ∧
      nullValueDR G guard R D p
        < MATE_LOWER + ((D : Int) - (k : Int) + 1) * EVAL_ROUGHNESS := by
  rw [nullValueDR_eq_guardOff G guard R hZ D p]
  exact leastMate_value_block G (fun _ => false) hF hQ hNM
    (noZugzwang_guardOff G) hcapf hLM hkD hspan

/-- Separation at reduction `R`: distinct least mate distances leave
more than one `EVAL_ROUGHNESS` between their declared values — the
driver's stopping tolerance still cannot straddle two mates. -/
theorem leastMate_value_separationR (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard R)
    {j k D : Nat} {p q : G.Pos}
    (hcapp : hasKingCapture G.toNullGame.toGame p = false)
    (hcapq : hasKingCapture G.toNullGame.toGame q = false)
    (hjp : LeastMate G j p) (hkq : LeastMate G k q) (hlt : j < k)
    (hjD : j + 1 ≤ D) (hkD : k + 1 ≤ D)
    (hspan : (D : Int) * EVAL_ROUGHNESS ≤ 21366) :
    EVAL_ROUGHNESS < nullValueDR G guard R D p - nullValueDR G guard R D q := by
  rw [nullValueDR_eq_guardOff G guard R hZ D p,
    nullValueDR_eq_guardOff G guard R hZ D q]
  exact leastMate_value_separation G (fun _ => false) hF hQ hNM
    (noZugzwang_guardOff G) hcapp hcapq hjp hkq hlt hjD hkD hspan

/-! ### The driver theorems at every reduction -/

/-- The engine's move choice at reduction `R`, within the driver's own
stopping tolerance of the best. -/
def NearMaximalChoiceR (G : QSGame) (guard : G.Pos → Bool) (R d : Nat)
    (ch : G.Pos → G.Pos) : Prop :=
  ∀ p, allIllegalB G p = false →
    ch p ∈ movesAbove G (val_lower (d + 1)) p ∧
      ∀ m ∈ movesAbove G (val_lower (d + 1)) p,
        nullValueDR G guard R d (ch p) ≤ nullValueDR G guard R d m + EVAL_ROUGHNESS

/-- The choice premise transfers to the guard-off instance. -/
theorem nearMaximalChoiceR_transfer (G : QSGame) (guard : G.Pos → Bool)
    (R d : Nat) (ch : G.Pos → G.Pos) (hZ : NoZugzwangR G guard R)
    (hch : NearMaximalChoiceR G guard R d ch) :
    NearMaximalChoice G (fun _ => false) d ch := by
  intro p hai
  obtain ⟨hmem, hmax⟩ := hch p hai
  refine ⟨hmem, fun m hm => ?_⟩
  have := hmax m hm
  rw [nullValueDR_eq_guardOff G guard R hZ d (ch p),
    nullValueDR_eq_guardOff G guard R hZ d m] at this
  exact this

/-- **Shortest-mate play at reduction `R`, odd form.** -/
theorem forcedMate_play_shortest_oddR (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (ch : G.Pos → G.Pos) (d : Nat)
    (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard R)
    (hch : NearMaximalChoiceR G guard R d ch) :
    ∀ (k : Nat) (p : G.Pos),
      k % 2 = 1 → k + 1 ≤ d + 1 → (d : Int) * EVAL_ROUGHNESS ≤ 21366 →
      hasKingCapture G.toNullGame.toGame p = false →
      ForcedMate G k p →
      MatesWithin G ch k p :=
  forcedMate_play_shortest_odd G (fun _ => false) ch d hF hQ hNM
    (noZugzwang_guardOff G)
    (nearMaximalChoiceR_transfer G guard R d ch hZ hch)

/-- **DISTANCE-TO-MATE OPTIMALITY, attacker half, at reduction `R`.** -/
theorem leastMate_play_shortestR (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (ch : G.Pos → G.Pos) (d : Nat)
    (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard R)
    (hch : NearMaximalChoiceR G guard R d ch)
    {k : Nat} {p : G.Pos}
    (hLM : LeastMate G k p) (hkd : k + 1 ≤ d + 1)
    (hspan : (d : Int) * EVAL_ROUGHNESS ≤ 21366)
    (hcapf : hasKingCapture G.toNullGame.toGame p = false) :
    MatesWithin G ch k p :=
  leastMate_play_shortest G (fun _ => false) ch d hF hQ hNM
    (noZugzwang_guardOff G)
    (nearMaximalChoiceR_transfer G guard R d ch hZ hch) hLM hkd hspan hcapf

/-- **Maximal resistance, defender half, at reduction `R`.** -/
theorem defence_resistsR (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (ch : G.Pos → G.Pos) (d : Nat)
    (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard R)
    (hch : NearMaximalChoiceR G guard R d ch)
    (hspan : (d : Int) * EVAL_ROUGHNESS ≤ 21366) :
    ∀ (N : Nat) (q : G.Pos),
      N ≤ d →
      hasKingCapture G.toNullGame.toGame q = false →
      ¬ Checkmated G q →
      (∀ i, ForcedlyMated G i q → N ≤ i + 1) →
      ResistsFor G ch N q :=
  defence_resists G (fun _ => false) ch d hF hQ hNM
    (noZugzwang_guardOff G)
    (nearMaximalChoiceR_transfer G guard R d ch hZ hch) hspan

/-- **DISTANCE-TO-MATE OPTIMALITY, both directions, at EVERY null
reduction** — the renewal's headline.  `R` is universally quantified:
the whole `[3..10]` range, odd and even alike, satisfies the same
optimality the shipped `R = 3` does, under the `R`-matched zugzwang
premise and nothing else new. -/
theorem dtm_optimalR (G : QSGame) (guard : G.Pos → Bool)
    (R : Nat) (ch : G.Pos → G.Pos) (d : Nat)
    (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard R)
    (hch : NearMaximalChoiceR G guard R d ch)
    (hspan : (d : Int) * EVAL_ROUGHNESS ≤ 21366) :
    (∀ {k : Nat} {p : G.Pos}, LeastMate G k p → k + 1 ≤ d + 1 →
        hasKingCapture G.toNullGame.toGame p = false →
        MatesWithin G ch k p) ∧
      (∀ {k : Nat} {q : G.Pos}, LeastMated G k q → k ≠ 0 → k + 1 ≤ d →
        hasKingCapture G.toNullGame.toGame q = false →
        ResistsFor G ch (k + 1) q) :=
  dtm_optimal G (fun _ => false) ch d hF hQ hNM
    (noZugzwang_guardOff G)
    (nearMaximalChoiceR_transfer G guard R d ch hZ hch) hspan

/-! ### The tuning range, witnessed

`dtm_optimalR` quantifies `R`, so the corollaries below are pure
instantiations — named so the even-reduction cases the old paragraph
declared impossible are visible in the build. -/

/-- The shipped reduction, recovered as an instance. -/
theorem dtm_optimal_R3 (G : QSGame) (guard : G.Pos → Bool)
    (ch : G.Pos → G.Pos) (d : Nat)
    (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard 3)
    (hch : NearMaximalChoiceR G guard 3 d ch)
    (hspan : (d : Int) * EVAL_ROUGHNESS ≤ 21366) :
    (∀ {k : Nat} {p : G.Pos}, LeastMate G k p → k + 1 ≤ d + 1 →
        hasKingCapture G.toNullGame.toGame p = false →
        MatesWithin G ch k p) ∧
      (∀ {k : Nat} {q : G.Pos}, LeastMated G k q → k ≠ 0 → k + 1 ≤ d →
        hasKingCapture G.toNullGame.toGame q = false →
        ResistsFor G ch (k + 1) q) :=
  dtm_optimalR G guard 3 ch d hF hQ hNM hZ hch hspan

/-- An EVEN reduction — the case the retired paragraph called
impossible.  Nothing about it is special. -/
theorem dtm_optimal_R4 (G : QSGame) (guard : G.Pos → Bool)
    (ch : G.Pos → G.Pos) (d : Nat)
    (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard 4)
    (hch : NearMaximalChoiceR G guard 4 d ch)
    (hspan : (d : Int) * EVAL_ROUGHNESS ≤ 21366) :
    (∀ {k : Nat} {p : G.Pos}, LeastMate G k p → k + 1 ≤ d + 1 →
        hasKingCapture G.toNullGame.toGame p = false →
        MatesWithin G ch k p) ∧
      (∀ {k : Nat} {q : G.Pos}, LeastMated G k q → k ≠ 0 → k + 1 ≤ d →
        hasKingCapture G.toNullGame.toGame q = false →
        ResistsFor G ch (k + 1) q) :=
  dtm_optimalR G guard 4 ch d hF hQ hNM hZ hch hspan

/-- The top of the tuning range. -/
theorem dtm_optimal_R10 (G : QSGame) (guard : G.Pos → Bool)
    (ch : G.Pos → G.Pos) (d : Nat)
    (hF : ValFloor G 192) (hQ : EvalQuiet G.toNullGame.toGame)
    (hNM : NoMaskedMobility G) (hZ : NoZugzwangR G guard 10)
    (hch : NearMaximalChoiceR G guard 10 d ch)
    (hspan : (d : Int) * EVAL_ROUGHNESS ≤ 21366) :
    (∀ {k : Nat} {p : G.Pos}, LeastMate G k p → k + 1 ≤ d + 1 →
        hasKingCapture G.toNullGame.toGame p = false →
        MatesWithin G ch k p) ∧
      (∀ {k : Nat} {q : G.Pos}, LeastMated G k q → k ≠ 0 → k + 1 ≤ d →
        hasKingCapture G.toNullGame.toGame q = false →
        ResistsFor G ch (k + 1) q) :=
  dtm_optimalR G guard 10 ch d hF hQ hNM hZ hch hspan

end Sunfish
