#!/usr/bin/env python3
"""Dump the classic engine's evaluation tables into the ctwin data format.

The C twin (sunfish.c) takes ALL evaluation data from this file at startup,
so an eval variant produced by any generator becomes a C engine by dumping
its tables here -- no recompilation.  The default dump is classic sunfish.py
at the repo root, post-padding (120-wide, piece values folded in), which is
the node-identity reference.

Format (line oriented, '#' comments ignored):
    piece <P> <N> <B> <R> <Q> <K>          # bare piece values (mate bounds)
    P <120 ints>                            # padded pst incl. piece value
    N <120 ints>
    B <120 ints>
    R <120 ints>
    Q <120 ints>
    K <120 ints>                            # midgame king (K_MID)
    KEND <120 ints>                         # endgame king table
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
import sunfish


def main():
    out = sys.stdout
    print("# classic sunfish tables, generated by gen_tables.py -- do not edit", file=out)
    print("piece", *(sunfish.piece[p] for p in "PNBRQK"), file=out)
    for p in "PNBRQK":
        print(p, *sunfish.pst[p], file=out)
    print("KEND", *sunfish.K_END, file=out)


if __name__ == "__main__":
    main()
